---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=100
      - PGID=100
      - VERSION=docker
    volumes:
      - /srv/dev-disk-by-label/containers/plex/config:/config
      - /srv/dev-disk-by-label/Series:/tv
      - /srv/dev-disk-by-label/Movies:/movies
    restart: unless-stopped
