version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '8082:80' # Public HTTP Port
      - '5443:443' # Public HTTPS Port
      - '8081:81' # Admin Web Port
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - /srv/dev-disk-by-label/containers/nginx/data:/data
      - /srv/dev-disk-by-label/containers/nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - db


  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: nginx-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - /srv/dev-disk-by-label/containers/nginx/data/mysql:/var/lib/mysql

networks:
  default:
    external:
      name: nginx-network

